### ISSUE TITLE
TypeError Data.Bytes is not a function  

### ISSUE THREAD

**Issue by prajnastra** [spacebudz/nebula#1]
I am getting this error once I added `nebula` to a nextjs project. The error is occured in `@spacebudz/nebula/esm/common/contract.types.js`.

**Comment by alessandrokonrad** [comment]
Do you use the right version of Lucid?

**Comment by prajnastra** [comment]
I have installed  `lucid@0.8.0` as the newer version showing me some error

**Comment by alessandrokonrad** [comment]
You need the latest `0.10.1`

**Comment by prajnastra** [comment]
Thanks now working.
